### ISSUE TITLE
Support more dav confiurations,

### ISSUE THREAD

**Issue by vbwagner** [Offerel/firefox_syncmarks#3]
1.  Why don't support http dav URLs? It is no always true than configuring SSL on servers inside closed local networks worth effort.

2. Why you implement HTTP auth by hand, instead of relying on builtin XMLHttpRequest capabilities?
It is much more powerful and supports more auth methods. For instance, Windows requires dav sites accessible from Windows Explorer  file manger to use digest authentication rather than basic. 

This would also prevent extension from disclosing password if user erroneously enter http URL instead of https (and check mentioned in p1  would be removed), because in this case XMLHttpRequest.send would first query server without Authorization header to find out supported types of authentication. And if user mistakenly entered http instead of https, server would refuse to request auth.

**Comment by Offerel** [comment]
Hello and thanks for your suggestions. I'll take a look at it in the coming days. But I think it makes sense to use https in internal networks as well. In principle, the user has to decide, but personally I would generally only use encryption internally. This costs nothing and the maintenance effort for the certificates is extremely low. 

Anyway, I take a look at it. If you are faster to create a pull request, I wouldn't be angry either.

**Comment by vbwagner** [comment]
Hello! You can look into [my clone of your repository](https://github.com/vbwagner/firefox_davmarks). 
It works with my DAV server, which uses digest authentication, but I'm not quite satifsfied 
how it handles mistyped passwords and how it syncs bookmarks between different computers, so I don't make pull request yet.

Use https on internal network places big overhead on local sysdmin. While he can use letsencrypt.org for extenal sites and automate certificate renewal once for all, internal sites by definicion shouldn't be disclosed to extenal entity such as certification authority. So, sysadmin have to run his own CA for internal network and somehow make all machintes  on the network (uncluding employee smartphones and tablets) trust it.  

Really problem is that only dav server with basic auth available to me at the moment of starting that thread was our internal one. It is intended to distribute operating system installation images and virual machine images. For such big files and fast network encryption overhead is not negligible, so it is configured to use https.

**Comment by Offerel** [comment]
Sorry for the long delay, i was at the holidays. I tested your solution yesterday. The primary problem with your solution is, that the request, including username and password, is displayed in the log files of all web servers and proxies. There they can be read without any problems. Especially if it is not a https connection, I see this as a big privacy and security problem.

Currently I am adding a better solution at the server side. In the current DEV version you now have the possibility to work with a JSON file via a WebDAV server as before or to synchronize the bookmarks via a PHP script. With the later, the sync logic can be extended and improved a lot. Roundcube works as a client here, just like Firefox. This also works with Chrome. So a cross-browser sync is possible. Opera and Edge should also work with this solution. For Chrome and other browsers you only have to adapt the AddOn accordingly, since I will at least not develop an AddOn myself, but others are welcome to do that.

**Comment by Offerel** [comment]
Most WebDAV servers I know, rely on Basic Auth instead of Digest.  In this case, a request in the form http(s)://username:password@serveraddress/path/to/webdav/ will be created if using your code. Only if the correct header is set explicitly specified, username and password are transferred as part of request.open. If the header is not set explicitly, as in your repository, the credentials become part of the URL requests. This is not strange, it is the normal behavior. However, the login works in both cases, only the form of the request is structured differently.

Digest Auth, on the other hand, can be safely ignored. The security gain through Digest is only infinitesimally small when using https. Basic Auth is supported by all systems, even Windows 7 up to and including Windows 10 works with Basic Auth, it is not correct that Basic Auth didn't work with Windows 10, it works without problems.

Why is PHP obscure or chaotic? It is relatively easy to learn and, unlike Python and Ruby, easier to use. Personally, I trust PHP more than the two languages I mentioned above. Just the setup and the generated overhead just at Python are just cruel. Of course there are also advantages with Python but they don't outweigh the disadvantages in any way. Since the AddOn primarily serves as a supplier for the bookmarks for Roundcube and Roundcube also uses PHP, it is only natural that a server part for the AddOn also uses PHP and do not open additional vulnerabilities in the system by installing a Python environment. Ultimately, it's more of a question of principle which language you prefer. There will probably never be an all-embracing answer. That ownCloud is not the best example for a good cloud solution, I have to agree with you. I would not use it either.

**Comment by vbwagner** [comment]
As far as I know http protocol, GET or PUT requests should contain just path without hostname not mention username and password. Requests in the form http(s)://user:password@hostname/path should be parsed on client side and never send over network. If Firefox behaves differently, it probably should be filed as bug of firefox.

As far. as I know how https proxy works, browser shouldn't disclose anything but hostame and port, dong CONNECT request.

So. I couldn't believe these your claims.

Really this your opinion means that you don't like to increase your userbase beyond RoundCube users
(and, in particular, include me). Alas. I've to search for other bookmark sync solution,





So I cannot believe that your claims.
