### ISSUE TITLE
Synology (Webdav)

### ISSUE THREAD

**Issue by west89** [Offerel/firefox_syncmarks#6]
I cannot connect to my Synology via Webdav.

`sting all bookmarks from server
11.05.2020, 02:01:05 - Info: Requesting all bookmarks from server
11.05.2020, 02:01:08 - Info: Requesting all bookmarks from server
11.05.2020, 02:01:09 - Info: Requesting all bookmarks from server
11.05.2020, 02:01:12 - Info: Requesting all bookmarks from server
11.05.2020, 02:01:13 - Info: Requesting all bookmarks from server
11.05.2020, 02:01:14 - Info: Requesting all bookmarks from server
`The connection looks like this:
The connection looks like this:

webdav:
http://IP:5005/Folder

webdavs:
https://IP:5006/Folder

Please note that this is not a real SSL certificate.

**Comment by Offerel** [comment]
When you request the bookmarks from the server with the import function, does the bookmarks.json file exists in the specified path on the server? Are there any entries in the logfiles on the server (acces.log / error.log) ?

**Comment by west89** [comment]
HTTP without port
![Bildschirmfoto-3](https://user-images.githubusercontent.com/42120960/82140690-e0777a00-9830-11ea-9ad0-7d35c4b9826f.png)

HTTPS with port
![Bildschirmfoto-5](https://user-images.githubusercontent.com/42120960/82140726-1caada80-9831-11ea-84a6-0b4b2308b8ad.png)

HTTP with port
![Bildschirmfoto-4](https://user-images.githubusercontent.com/42120960/82140697-f8e79480-9830-11ea-89d5-570201960b7c.png)

Per http:// without port it is successful but no .json is created.
As SSL certificate lets encrypt is used.

**Comment by Offerel** [comment]
You say, you use a Letsencrypt certificate, but on the other side you didn't make use of it. Letsencrypt works on domaine base and not on the IP address. If the IP address isn't part of certificate, validation of the certificate will fail. So you must use the same domain in the URL, as in the certificate. The example without https didn't make use of a certificate, that's why your login works. Additionally, i don't want to support unvalidated https traffic. I don't know whats going on, when you import a self-generated cert in your browser, maybe this will work.

Regarding usage of ports: I haven't tested using no-standard ports. I will have a look in to this and how i can support that.

Regarding the missing json file: Do you have a bookmark.json file generated? It will not be there, after the first login, without exporting bookmarks first. This is by design, because you would overwrite otherwise a existing file.
