### ISSUE TITLE
firefox 79.0 addon not working

### ISSUE THREAD

**Issue by kartozar** [Offerel/firefox_syncmarks#7]
I installed the extension, configured it, and a synstarks folder was created in my google disk, but it’s always empty and bookmarks are not synchronized, and nothing is written to the folder. the setup is the same at work and at home. firefoch 79.0 32 be.

**Comment by Offerel** [comment]
At least here, it works without any problem with Firefox 79.0.

What is a Google disk and how exactly looks your setup?

**Comment by kartozar** [comment]
Google disk is a Google drive. my installation looks like I install the extension, then go into its settings, get a token from Google Drive, and insert it in the authorization section in the extension settings. then a syncmark folder is created on the Google drive, and nothing is synchronized.

**Comment by Offerel** [comment]
I have never used Google drive, however this seems to be no standard WebDAV implementation. Currently only http basic authentication with WebDAV is supported. 

I have no idea if Google drive is using standard http commands, authentication and so on. But when I read something about some token, im not sure if that's the case with Google drive. 

Can you please test a standard, not Google related WebDAV folder?

**Comment by kartozar** [comment]
storage does not work not only on Google firewood, but also on dropboxes, also the information is not stored, and nothing is synchronized. And how should it work? what to use to make it work?

**Comment by Offerel** [comment]
To my knowledge, Dropbox is not using WebDAV as protocol, if this has changed, please correct me. That's why Dropbox will not work with this extension. Some years ago there was a third-party WebDAV to Dropbox adapter, but i fear this isn't working anymore. For Google Drive I'm not sure if it supports WebDAV standard, you should ask Google support for this and the correct URL to enter as path.

But there are many free WebDAV implementation's available. You can also use NextCloud, OwnCloud, SabreDAV and some other to host your own WebDAV server. All what supports standard WebDAV, will work.
